StrictMode translation to spanish
reactjs/es.react.dev pull request #656
Opened 2023-04-19 21:58 UTC by Dazzae-exe

### Strict Mode
- Traducción a español de su doc.

Encantado de corregir algún cambio que se necesite asap.

2023-04-24 14:07 UTC, Dazzae-exe commented
@carburo Buen día carburo, espero puedas chequear el PR en cualquier momento. Saludos y un gran comienzo de semana 👍🏻.

2023-04-27 18:17 UTC, mateoguzmana reviewed
Excelente trabajo, se ve muy bien en general. Solo noté unas cosas pequeñas.

2023-04-27 18:17 UTC, mateoguzmana commented on src/content/reference/react/StrictMode.md
> +A pesar de, Strict Mode chequea **solo corre en desarrollo,** ayudan a usted a encontrar errores que ya existen en tu código, pero pueden ser complicados reproducirlo de forma confiable en producción
```suggestion
A pesar de que, Strict Mode chequea **que solo corra en desarrollo,** te ayudará a encontrar errores que ya existen en tu código, pero pueden ser complicado reproducirlos de forma confiable en producción. Strict Mode, te permite corregir errores antes que tus usuarios los reporten.
```

2023-04-27 18:17 UTC, mateoguzmana commented on src/content/reference/react/StrictMode.md
> +Strict Mode, habilitá chequeos adicionales de solo desarrollo para el árbol de componentes entero dentro del componente `<StrictMode>`. Estos chequeos ayudan a encontrar errores comunes en tus compon
```suggestion
Strict Mode, habilita chequeos adicionales de solo desarrollo para el árbol de componentes entero dentro del componente `<StrictMode>`. Estos chequeos ayudan a encontrar errores comunes en tus componentes al principio del proceso de desarrollo.
```

2023-04-27 18:17 UTC, mateoguzmana commented on src/content/reference/react/StrictMode.md
> +**Todo estos chequeos son solo desarrollo y no afectan la compilación de producción.**
```suggestion
**Todos estos chequeos son solo desarrollo y no afectan la compilación de producción.**
```

2023-04-27 18:17 UTC, mateoguzmana commented on src/content/reference/react/StrictMode.md
> +[Lea más sobre la implementación de la limpieza de Effect.](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)
```suggestion
[Lee más sobre la implementación de la limpieza de Effect.](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)
```

2023-04-28 13:35 UTC, Dazzae-exe commented
@mateoguzmana Muchas gracias Mateo, ya hice push de los cambios que me pediste 👍🏻

2023-04-28 22:21 UTC, soyjuanmacias commented on src/content/reference/react/StrictMode.md
> +`<StrictMode>` permite encontrar errores comunes en los componentes al comienzo del desarrollo.
¿Sería mas correcto `le permite encontrar`? como traducción de `let you find`

2023-04-28 22:37 UTC, soyjuanmacias commented on src/content/reference/react/StrictMode.md
> +Use `StrictMode` para habilitar comportamientos de compilación y advertencias adicionales para el árbol de componentes que se encuentra dentro:
Habla de comportamientos de desarrollo, no de compilación.

`para habilitar comportamientos de desarrollo adicionales y advertencias para el árbol de componentes dentro`

2023-05-02 02:31 UTC, carburo requested changes
¡Hola, @Dazzae-exe! ¡Muchas gracias por tu contribución! Te he dejado varios comentarios sobre algunos aspectos que deberías revisar antes de poder mezclar este PR.

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Strict Mode puede también ayudar a encontrar bugs en [Effects.](/learn/synchronizing-with-effects)
```suggestion
El Modo Estricto puede también ayudar a encontrar errores en los [Efectos.](/learn/synchronizing-with-effects)
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Cada Effect tiene algún código configurado y podría tener algún código de limpieza. Normalmente, React llama la configuración cuando el componente *mounts* (se añadió a la pantalla) y llama la limpie
```suggestion
Cada Efecto tiene algún código de configuración y podría tener algún código de limpieza. Normalmente, React llama al código de configuración cuando el componente *se monta* (se añadió a la pantalla) y llama a la limpieza cuando el componente *se desmonta* (se eliminó de la pantalla). React entonces llama a la limpieza y configuración de nuevo si sus dependencias cambiaron desde el último renderizado.
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Cuando Strict Mode está prendida, React va también ejecutar **Un ciclo extra de configuración+limpieza en desarrollo por cada Effect.** Esto podría ser sorpresivo, pero esto ayuda a revelar errores s
```suggestion
Cuando Strict Mode está activo, React también ejecutará **un ciclo extra de configuración+limpieza en desarrollo por cada Efecto.** Esto podría sorprender, pero ayuda a revelar errores sutiles que son difíciles de detectar manualmente.
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +**Aquí tienes un ejemplo para ilustrarte como volver a renderizar Effects en Strict Mode ayuda a encontrar errores al principio.**
```suggestion
**Aquí tienes un ejemplo para ilustrarte cómo volver a renderizar Efectos en Modo Estricto ayuda a encontrar errores al principio.**
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Hay un problema con este código pero no podría ser limpiado inmediatamente.
```suggestion
Hay un problema con este código pero podría no quedar claro inmediatamente.
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Para hacer este problema más obvio, implementemos una característica. En el siguiente ejemplo, `roomId` no está hard-codeado. En vez, el usuario puede seleccionar el `roomId` que quiere conectarse de
```suggestion
Para hacer este problema más obvio, implementemos una funcionalidad. En el siguiente ejemplo, `roomId` no está codificado de forma fija. En cambio, el usuario puede seleccionar el `roomId` al que quiere conectarse desde un dropdown. Haz clic en "Open chat" y luego selecciona diferentes salas de chat una por una. Mantén la cuenta del número de conexiones activas en la consola:
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Vas a darte cuenta de que el número de conexiones abiertas siempre se mantiene creciendo. En una aplicación real, esto causaría problemas de rendimiento y de red. El problema es que [tu Effect esta f
```suggestion
Vas a darte cuenta de que el número de conexiones abiertas siempre se mantiene creciendo. En una aplicación real, esto causaría problemas de rendimiento y de red. El problema es que a [tu Efecto le falta una función de limpieza:](/learn/synchronizing-with-effects#step-3-add-cleanup-if-needed)
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Ahora que tu Effect “limpia” después de sí mismo y destruye las conexiones obsoletas, la fuga está resuelta. Sin embargo, date cuenta de que el problema no se convirtió visible hasta que se había aña
```suggestion
Ahora que tu Effect “hace una limpieza” al concluir y destruye las conexiones obsoletas, la fuga está resuelta. Sin embargo, date cuenta de que el problema no se hizo visible hasta que añadiste más funcionaliades (el cuadro de selección).
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +**En el ejemplo original, el error no era obvio. Ahora envolvamos el código original (buggy) en `<StrictMode>`:**
```suggestion
**En el ejemplo original, el error no era obvio. Ahora envolvamos el código original (con errores) en `<StrictMode>`:**
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +**Con Strict Mode, ves inmediatamente que hay un problema** (el número de conexiones activas salta a dos[2]). Strict Mode ejecuta un ciclo extra configuración+limpieza por cada Effect. Este Effect no
```suggestion
**Con Modo Estricto, ves inmediatamente que hay un problema** (el número de conexiones activas salta a 2). El Modo Estricto ejecuta un ciclo extra de configuración+limpieza por cada Efecto. Este Efecto no tiene lógica de limpieza, por lo que crea una conexión extra, pero no la destruye. Esto es una pista de que te falta una función de limpieza.
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Strict Mode te permite notar semejantes errores al principio del proceso. Cuando tú corriges tu Effect al añadir una función de limpieza en Strict Mode, tu *también* corriges varios posibles futuros
```suggestion
El Modo Estricto te permite notar este tipo de errores al principio del proceso. Cuando corriges tu Efecto al añadir una función de limpieza en Modo Estricto, *también* corriges varios posibles futuros errores en producción como el cuadro de selección anterior:
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Date cuenta de como la cuenta de conexiones activas en la consola no se mantiene creciendo mucho más.
```suggestion
Date cuenta de como la cuenta de conexiones activas en la consola ya no sigue creciendo.
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +Sin Strict Mode, es fácil pasar por alto que tu Effect necesita limpieza. Al ejecutar *configuración → limpieza → configuración* en vez de *configuración* por tu Effect en desarrollo, El Strict Mode
```suggestion
Sin Modo Estricto, es fácil pasar por alto que tu Efecto necesita limpieza. Al ejecutar *configuración → limpieza → configuración* en vez de *configuración* para tu Efecto en desarrollo, el Modo Estricto hizo que la lógica de limpieza faltante fuera más notable.
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +[Lee más sobre la implementación de la limpieza de Effect.](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)
```suggestion
[Lee más sobre la implementación de la limpieza de los Efectos.](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +### Arreglando advertencias obsoletas permitidas por Strict Mode {/*fixing-deprecation-warnings-enabled-by-strict-mode*/}
```suggestion
### Arreglar advertencias de código obsoleto habilitadas en el Modo Estricto {/*fixing-deprecation-warnings-enabled-by-strict-mode*/}
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +* `UNSAFE_` ciclo de vida de métodos de clase como [`UNSAFE_componentWillMount`](/reference/react/Component#unsafe_componentwillmount). [Ver alternativas.](https://reactjs.org/blog/2018/03/27/update-
```suggestion
* Métodos de ciclo de vida `UNSAFE_` como [`UNSAFE_componentWillMount`](/reference/react/Component#unsafe_componentwillmount). [Ver alternativas.](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#migrating-from-legacy-lifecycles) 
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +* Herencia context ([`childContextTypes`](/reference/react/Component#static-childcontexttypes), [`contextTypes`](/reference/react/Component#static-contexttypes), y [`getChildContext`](/reference/reac
```suggestion
* API antigua de contexto ([`childContextTypes`](/reference/react/Component#static-childcontexttypes), [`contextTypes`](/reference/react/Component#static-contexttypes), y [`getChildContext`](/reference/react/Component#getchildcontext)). [Ver alternativas.](/reference/react/createContext)
```

2023-05-02 02:31 UTC, carburo commented on src/content/reference/react/StrictMode.md
> +* Herencia de strings refs ([`this.refs`](/reference/react/Component#refs)). [Ver alternativas.](https://reactjs.org/docs/strict-mode.html#warning-about-legacy-string-ref-api-usage)
```suggestion
* Antiguas refs de strings ([`this.refs`](/reference/react/Component#refs)). [Ver alternativas.](https://reactjs.org/docs/strict-mode.html#warning-about-legacy-string-ref-api-usage)
```

2023-05-04 15:44 UTC, merged