translate: react hooks to spanish
reactjs/es.react.dev pull request #663
Opened 2023-04-27 15:43 UTC by Dazzae-exe

## Traducción de React Hooks
Feliz de poder seguir aportando a nuestra comunidad. Cualquier cambio que se necesite, estoy al pendiente @carburo. 

[**react hooks**](https://react.dev/reference/react).

2023-04-27 19:36 UTC, mateoguzmana commented on src/content/reference/react/index.md
> +El *Refs* permite a un componente [mantener alguna información que no es utilizada para renderización](/learn/referencing-values-with-refs) como un nodo del DOM o un timeout ID. A diferencia con el e
```suggestion
Los *Refs* le permiten a un componente [mantener alguna información que no es utilizada para renderización](/learn/referencing-values-with-refs) como un nodo del DOM o un timeout ID. A diferencia con el estado, actualizando un *ref* no vuelve a renderizar tu componente. Los *Refs* son una “escotilla de escape” del paradigma de React. Son útiles cuando tú necesitas trabajar con sistemas no-React, semejantes como el navegador incorporado de APIs.
```

2023-04-27 19:36 UTC, mateoguzmana commented on src/content/reference/react/index.md
> +* [`useEffect`](/reference/react/useEffect) conecta un componente a sistema externo.
```suggestion
* [`useEffect`](/reference/react/useEffect) conecta un componente a un sistema externo.
```

2023-04-27 19:36 UTC, mateoguzmana commented on src/content/reference/react/index.md
> +*Hook Effect* son una “escotilla de escape” del paradigma de React. No utilices *Effects* para guiar el flujo de los datos de tu aplicación. Si no estás interactuando con un sistema externo, [no podr
```suggestion
*Hook Effect* son una “escotilla de escape” del paradigma de React. No utilices *Effects* para guiar el flujo de los datos de tu aplicación. Si no estás interactuando con un sistema externo, [puede que no necesites un Hook Effect.](/learn/you-might-not-need-an-effect)
```

2023-04-27 19:36 UTC, mateoguzmana commented on src/content/reference/react/index.md
> +Algunas veces, no podrás saltar el doble renderizado porque la pantalla actualmente necesita una actualización. En ese caso, tú puedes mejorar el rendimiento separando las actualizaciones de bloqueo
```suggestion
Algunas veces, no podrás saltar el doble renderizado porque la pantalla actualmente necesita una actualización. En ese caso, tú puedes mejorar el rendimiento separando las actualizaciones de bloqueo que deben ser síncronas (como al escribir dentro de una entrada) de actualizaciones no bloqueadas, las cuáles no necesitan bloquear la interfaz de usuario (como actualizar un gráfico).
```

2023-04-27 19:36 UTC, mateoguzmana commented on src/content/reference/react/index.md
> +Tú también puedes [definir tus propios Hooks personalizados](/learn/reusing-logic-with-custom-hooks#extracting-your-own-custom-hook-from-a-component) como funciones JavaScript.
```suggestion

Tú también puedes [definir tus propios Hooks personalizados](/learn/reusing-logic-with-custom-hooks#extracting-your-own-custom-hook-from-a-component) como funciones JavaScript.
```

2023-05-01 16:38 UTC, mateoguzmana approved these changes

2023-05-03 03:50 UTC, carburo requested changes
Hola @Dazzae-exe, gracias por tu contribución.
Voy a dejarte una reseña preliminar para que hagas un segundo paso por el documento teniendo en cuenta estos aspectos:
- Los títulos solo deben tener mayúscula inicial [ver guía de estilo](https://github.com/reactjs/es.react.dev/wiki/Gu%C3%ADa-de-estilo#traducción-de-los-t%C3%ADtulos)
- Debes mantener los números de línea del artículo original
- *“React Hooks”* se traduce como «Hooks de React» [ver glosario](https://github.com/reactjs/es.react.dev/wiki/Glosario)
- *“Effect”* se traduce como «Efecto» 
- *“Context”* se traduce como «Contexto» cuando se refiere al concepto dentro de React, no una referencia explícita a la API Context (por ejemplo: Context.Provider).
- Se mantiene la escritura de «ref(s)» como nombre femenino (no «referencia»).
- Vuelve a realizar una revisión de los títulos, en particular el título de la página cambia el sentido original «Incorporación de React Hooks» vs. «Hooks integrados de React»

2023-05-12 23:59 UTC, merged