Translation escape hatches
reactjs/es.react.dev pull request #669
Opened 2023-04-30 22:15 UTC by Juamez

Agrego la traducción de la sección Escape Hatches.

- Me tomé el atrevimiento de traducir el tag que aparece debajo del título principal para que la sección estuviera lo más completa posible en su traducción, además del título de la sección del WIP.

- También corregí un título en el sidebar tomando de referencia la guía de traducción.

Estoy atento a cualquier correción. 😄

2023-05-01 17:29 UTC, mateoguzmana reviewed
Gracias por la contribución @Juamez!

Te dejé un par de comentarios de cosas pequeñas que noté.

2023-05-01 17:29 UTC, mateoguzmana commented on src/content/learn/escape-hatches.md
> +* [Como compartir lógica entre componentes](/learn/reusing-logic-with-custom-hooks)
```suggestion
* [Cómo compartir lógica entre componentes](/learn/reusing-logic-with-custom-hooks)
```

Estas lineas son interrogativas, por lo tanto la tilde. Lo mismo para el resto de las otras lineas desde la 13 a la 20

2023-05-01 17:29 UTC, mateoguzmana commented on src/content/learn/escape-hatches.md
> +      Hazme clic!
```suggestion
      ¡Hazme clic!
```

2023-05-01 17:29 UTC, mateoguzmana commented on src/content/learn/escape-hatches.md
> +Lee **[Referenciar Valores con Refs](/learn/referencing-values-with-refs)** para aprender como usar las refs y recordar información.
```suggestion
Lee **[Referenciar valores con Refs](/learn/referencing-values-with-refs)** para aprender como usar las refs y recordar información.
```

2023-05-01 17:29 UTC, mateoguzmana commented on src/content/learn/escape-hatches.md
> +Al igual que un estado, las refs son retenidas por React entre nuevos renderizados. Sin embargo, al asignar el estado se vuelve a renderizar el componente. Cambiar la ref no lo hace!. Puedes acceder
```suggestion
Al igual que un estado, las refs son retenidas por React entre nuevos renderizados. Sin embargo, al asignar un nuevo valor al estado se vuelve a renderizar el componente. ¡Cambiar el valor de la ref no lo hace! Puedes acceder al valor actual de esa ref a través de la propiedad `ref.current`.
```

2023-05-01 17:29 UTC, mateoguzmana commented on src/content/learn/escape-hatches.md
> +En este ejemplo, el hook personalizado  `usePointerPosition` rastrea la posición del cursor, mientras que el hook personalizado  `useDelayedValue` retorna un valor que esta "rezagado" con respecto al
```suggestion
En este ejemplo, el hook personalizado `usePointerPosition` rastrea la posición del cursor, mientras que el hook personalizado  `useDelayedValue` retorna un valor que esta "rezagado" con respecto al valor que le pasaste por un cierto número de milisegundos. Mueve el cursor sobre el área de vista previa del sandbox  para ver un rastro de puntos en movimiento que siguen al cursor:
```

2023-05-02 17:32 UTC, Juamez commented
> Gracias por la contribución @Juamez!
> 
> Te dejé un par de comentarios de cosas pequeñas que noté.

Hola, gracias por la revisión @mateoguzmana.

Ya hice los arreglos de tus comentarios, quedo atento a cualquier cosa.

2023-05-03 17:06 UTC, mateoguzmana commented
@Juamez podrías revertir los cambios de los archivos del PR con excepción a `src/content/learn/escape-hatches.md`?

El equipo de React recomienda no traducir elementos de la UI en el momento para evitar conflictos en el futuro, ya que estos van a cambiar o pueden cambiar un poco pronto.

> Keep in mind translating UI is best done closer to the end. We plan to make non-trivial code changes to the repo over the next few months. So it's best to focus on the content rather than on UI components.

2023-05-03 22:58 UTC, carburo requested changes
¡Hola @Juamez! Gracias por tu colaboración en traducir esta página que es particularmente extensa. Te he dejado algunos comentarios sobre algunos aspectos que noté al revisarla.

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +Algunos componentes necesitan sincronizarse con sistemas externos. Por ejemplo, es posible que desees controlar un componente que no sea de React basado en el estado de React, establecer una conexión
https://github.com/reactjs/es.react.dev/wiki/Gu%C3%ADa-de-estilo#mayúsculas-en-terminolog%C3%ADa-de-react

Revisa otros lugares del documento con la misma situación.
```suggestion
Algunos componentes necesitan sincronizarse con sistemas externos. Por ejemplo, es posible que desees controlar un componente que no sea de React basado en el estado de React, establecer una conexión a un servidor, enviar reporte de analíticas cuando un componente aparece en la pantalla. A diferencia de los manejadores de eventos, que permiten manejar eventos concretos, los *Efectos* te permiten ejecutar algún código después de renderizar. Úsalos para sincronizar tu componente con un sistema externo a React.
```

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +Algunos efectos pueden "limpiarse" por sí mismos. Por ejemplo, un efecto que establece una conexión a un servidor de chat debería retornar una *función de limpieza* que le dice a React como desconect
```suggestion
Algunos efectos pueden "limpiarse" por sí mismos. Por ejemplo, un efecto que establece una conexión a un servidor de chat debería retornar una *función de limpieza* que le dice a React como desconectar tu componente de ese servidor:
```

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +React proporciona una regla al linter para comprobar que hayas especificado correctamente las dependencias de tus efectos. Si olvidas de especificar `roomId` en la lista de dependencias en el ejemplo
https://www.rae.es/dpd/olvidar
En español estándar «te olvidas de especificar» u «olvidas especificar».
```suggestion
React proporciona una regla al linter para comprobar que hayas especificado correctamente las dependencias de tus efectos. Si olvidas especificar `roomId` en la lista de dependencias en el ejemplo anterior, el linter encontrará ese error automáticamente.
```

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +Esta sección describe una **API experimental que aún no se ha publicado** en una version estable de React.
```suggestion
Esta sección describe una **API experimental que aún no se ha publicado** en una versión estable de React.
```

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +Los eventos manejadores únicamente se vuelven a ejecutar cuando realizas de nuevo la misma interacción. A diferencia de los eventos manejadores, los efectos se vuelven a sincronizar si alguno de los
https://github.com/reactjs/es.react.dev/wiki/Glosario#:~:text=manejador%20de%20eventos
Revisa ocurrencias como esta en el resto del documento
```suggestion
Los manejadores de eventos únicamente se vuelven a ejecutar cuando realizas de nuevo la misma interacción. A diferencia de los manejadores de eventos, los efectos se vuelven a sincronizar si alguno de los valores que leen, como props o estados, son diferentes a los del último renderizado. Algunas veces, quieres una mezcla de ambos comportamientos: un efecto que se vuelve a ejecutar en respuesta de algunos valores.
```

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +Esto no es lo ideal. Quieres volver a conectar con el chat únicamente si el `roomId` ha cambiado. Cambiar el `tema` no debería volver a conectarse con el chat! Mueve el código que lee el `tema` fuera
`theme` no debe traducirse porque se está refiriendo a una variable en el código. Te pongo una sugerencia de cómo manejar este caso.
```suggestion
Esto no es lo ideal. Quieres volver a conectar con el chat únicamente si el `roomId` ha cambiado. ¡Cambiar el tema (mediante `theme`) no debería provocar una reconexión con el chat! Mueve el código que lee `theme` fuera de tu Efecto hacia un *Evento de Efecto*:
```

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +    showNotification('Conectado!', theme);
Revisa en otras partes de la página en que puedan también faltar los signos de apertura.
```suggestion
    showNotification('¡Conectado!', theme);
```

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +Fíjate que no empezaste editando la lista de dependencia para eliminar la dependencia `options`. Eso sería un error. En lugar de eso, cambiaste el código alrededor así que la dependencia se volvió *i
```suggestion
Fíjate que no empezaste editando la lista de dependencias para eliminar la dependencia `options`. Eso sería un error. En lugar de eso, cambiaste el código alrededor así que la dependencia se volvió *innecesaria.* Piensa en la lista de dependencias como una lista de todos los valores reactivos utilizados por el código de tu efecto. Tú no escogiste intencionadamente que poner en esa lista. La lista describe tu código. Para cambiar la lista de dependencias, cambia el código.
```

2023-05-03 22:58 UTC, carburo commented on src/content/learn/escape-hatches.md
> +React viene con hooks incorporados como `useState`, `useContext`, y `useEffect`. Algunas veces, desearás que existiera un hook para un propósito especifico: por ejemplo, para llamar datos, para saber
El término que estamos uando para mantener la consistencia es «Hooks integrados».
https://github.com/reactjs/es.react.dev/wiki/Glosario
```suggestion
React viene con Hooks integrados como `useState`, `useContext`, y `useEffect`. Algunas veces, desearás que existiera un hook para un propósito especifico: por ejemplo, para llamar datos, para saber si el usuario está conectado, o para conectarse a una sala de chat. Para realizar esto, puedes crear tus propios hooks de acuerdo a las necesidades de tu aplicación.
```

2023-05-03 23:03 UTC, Juamez commented
> @Juamez podrías revertir los cambios de los archivos del PR a excepción de `src/content/learn/escape-hatches.md`?
> 
> El equipo de React recomienda no traducir elementos de la UI en el momento para evitar conflictos en el futuro, ya que estos van a cambiar o pueden cambiar un poco pronto.
> 
> > Keep in mind translating UI is best done closer to the end. We plan to make non-trivial code changes to the repo over the next few months. So it's best to focus on the content rather than on UI components.

Gracias por la aclaración @mateoguzmana. 👍

2023-05-06 03:38 UTC, Juamez commented
Hola @carburo, gracias por revisar y dejar tus comentarios, he aplicado tus sugerencias y otros errores que encontré, igual si surge algo más, sigo atento, gracias.

2023-05-06 03:58 UTC, carburo approved these changes
¡Gracias por tu colaboración! Revertí los cambios de las mayúsculas en «ref», con base en el mismo uso de mayúsculas que en la documentación original para términos específicos de React.

2023-05-06 03:59 UTC, merged