Translate renderToReadableStream
reactjs/es.react.dev pull request #670
Opened 2023-04-30 22:20 UTC by mikelmiras

¡Buenas noches! Ya he acabado la traducción de la página renderToReadableStream. Si hay que modificar algo, estoy abierto a ello :)

2023-05-01 16:56 UTC, mateoguzmana requested changes
Gracias por la contribución @mikelmiras!

Andaba a punto de empezar la revisión del PR pero noté una inconsistencia en el diff con los espacios. Quizás es tu linter local? Sería bueno revisar eso

![image](https://user-images.githubusercontent.com/20783123/235492215-c2b863e1-9ad1-4c82-91a0-d172bf731e37.png)

2023-05-02 08:04 UTC, mikelmiras commented
> Gracias por la contribución @mikelmiras!
> 
> 
> 
> Andaba a punto de empezar la revisión del PR pero noté una inconsistencia en el diff con los espacios. Quizás es tu linter local? Sería bueno revisar eso
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/20783123/235492215-c2b863e1-9ad1-4c82-91a0-d172bf731e37.png)
> 
> 

Sí, me acabo de fijar que visual studio code me añade las tabulaciones automáticamente, lo soluciono y actualizo, muchas gracias! =ad

2023-05-04 17:26 UTC, mateoguzmana reviewed
¡Todo se ve muy bien en general @mikelmiras!

Te he dejado un par de cosas para que revises.

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +* `reactNode`: Nodo de React que quieras renderizar a HTML. Por ejemplo, un elemento JSX como `<App />`. Se presupone que representará el documento completo, por lo que el componente `App` debería re
```suggestion
* `reactNode`: Es un nodo de React que quieres renderizar en HTML. Por ejemplo, un elemento JSX como `<App />`. Se presupone que representará el documento completo, por lo que el componente `App` debería renderizar la etiqueta `<html>`.
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +  * **opcional** `namespaceURI`: Un string con la raíz del [namespace URI](https://developer.mozilla.org/es/docs/Web/API/Document/createElementNS#namespace_uris_válidos) para el stream. Por defecto s
Kudos por encontrar la URL con traducción al castellano 🥇

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +  * **opcional** `nonce`: Un string [`nonce`](http://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#nonce) que le permita al script la [`script-src` política de contenido seguro (CSP)](http
```suggestion
  * **opcional** `nonce`: Un string [`nonce`](http://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#nonce) que le permite al script la [`script-src` política de contenido seguro (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src).
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +  * **opcional** `onError`: Retrollamada que se activa cuando ocurre un error en el servidor, sea [recuperable](#recovering-from-errors-outside-the-shell) o [no.](#recovering-from-errors-inside-the-s
```suggestion
  * **opcional** `onError`: Callback que se activa cuando ocurre un error en el servidor, sea [recuperable](#recovering-from-errors-outside-the-shell) o [no.](#recovering-from-errors-inside-the-shell) Por defecto, solo ejecuta `console.error`. Si lo sobreescribes para [registrar errores en el servidor,](#logging-crashes-on-the-server) asegúrate que sigas llamando a `console.error`. También puedes usarlo para [ajustar el código de estado](#setting-the-status-code) antes de que el shell sea emitido.
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +- Si el [shell](#specifying-what-goes-into-the-shell) se renderizó satisfactoriamente, la promesa se resolverá a un [Readable Web Stream.](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStr
```suggestion
- Si el [shell](#specifying-what-goes-into-the-shell) se renderizó satisfactoriamente, la promesa se devolverá a un [Readable Web Stream.](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream)
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +- Si el renderizado del shell falla, la promesa será rechazada. [Usa esto para mostrar un shell mediante retrollamada.](#recovering-from-errors-inside-the-shell)
```suggestion
- Si el renderizado del shell falla, la promesa será rechazada. [Usa esto para mostrar un shell mediante un callback.](#recovering-from-errors-inside-the-shell)
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +### Renderizar árbol de React como HTML a Readable Web Stream {/*rendering-a-react-tree-as-html-to-a-readable-web-stream*/}
```suggestion
### Renderizar un árbol de React como HTML a un Readable Web Stream {/*rendering-a-react-tree-as-html-to-a-readable-web-stream*/}
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +  ```
```suggestion
```
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +En el cliente, tu script de arranque debería [hidratar el `document` entero con una llamada a `hydrateRoot`:](/reference/react-dom/client/hydrateRoot#hydrating-an-entire-document)
```suggestion
En el cliente, tu script inicial debería [hidratar el `document` entero con una llamada a `hydrateRoot`:](/reference/react-dom/client/hydrateRoot#hydrating-an-entire-document)
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +Las URL finales de los recursos (como los archivos CSS y JS) suelen ser hasheadas después de la compilación. Por ejemplo, en lugar de `estilos.css` podrías tener `estilos.123456.css`. Hashear nombres
```suggestion
Las URL finales de los recursos (como los archivos CSS y JS) suelen ser hasheadas después de la compilación. Por ejemplo, en lugar de `estilos.css` podrías tener `estilos.123456.css`. El hasheo de nombres de archivos estáticos garantiza que cada versión distinta del mismo recurso tendrá un nombre de archivo diferente. Esto es útil porque te permite activar de forma segura el almacenamiento en caché a largo plazo para recursos estáticos: un archivo con un nombre característico nunca cambiaría su contenido.
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +Sin embargo, si no conoces las URLs de los recursos hasta después de tener la build, no te será posible ponerlas en el código fuente. Por ejemplo, *hardcod*eas `"/styles.css"` en JSX, esto no funcion
```suggestion
Sin embargo, si no conoces las URLs de los recursos hasta después de tener el build, no te será posible ponerlas en el código fuente. Por ejemplo, si hardcodeas `"/styles.css"` en JSX, esto no funcionaría, puesto que es una URL relativa. Para mantenerlas fuera del código fuente, tu componente raíz puede leer el nombre real de un archivo a través de un mapa pasado como propiedad:
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +// Necesitarás obtener este JSON a través de tus herramientas de compilación. Por ejemplo, leyéndolo desde laconsola de compilación
```suggestion
// Necesitarás obtener este JSON a través de tus herramientas de compilación. Por ejemplo, leyéndolo desde la consola de compilación
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +**Solo las fuentes de información "Suspense-enabled" activarán el componente Suspense.** Se incluyen:
```suggestion
**Solo las fuentes de información "Suspense-enabled" activarán el componente Suspense.** Estas incluyen:
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +- Código de componentes lazy-loading de [`lazy`](/reference/react/lazy)
```suggestion
- Código de componentes lazy-loading con [`lazy`](/reference/react/lazy)
```

2023-05-04 17:26 UTC, mateoguzmana commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +Al [dividir la app](#specifying-what-goes-into-the-shell) en shell (por encima de los perímetros `<Suspense>`) y el resto de contenido, ya se ha solucionado una parte de este problema. Si el shell fa
```suggestion
Al [dividir la app](#specifying-what-goes-into-the-shell) en el shell (por encima de los perímetros `<Suspense>`) y el resto de contenido, ya se ha solucionado una parte de este problema. Si el shell falla, el bloque `catch` te permitirá establecer el código de estado del error. De lo contrario, sabes que la app se podrá recuperar en el cliente, por lo que puedes enviar un "OK".
```

2023-05-06 13:40 UTC, mateoguzmana approved these changes

2023-05-06 13:43 UTC, merged