Translate Synchronizing-with-effects to Spanish
reactjs/es.react.dev pull request #673
Opened 2023-05-02 22:28 UTC by NahuelDev

#500 

Hola! Encantado de corregir cualquier cambio que se necesite.

2023-05-04 16:55 UTC, mateoguzmana commented on src/sidebarLearn.json
¡Gracias por contribuir @NahuelDev!

Podrías revertir los cambios de este archivo? El equipo de React recomienda no traducir elementos de la UI en el momento para evitar conflictos en el futuro, ya que estos van a cambiar o pueden cambiar un poco pronto.

> Keep in mind translating UI is best done closer to the end. We plan to make non-trivial code changes to the repo over the next few months. So it's best to focus on the content rather than on UI components.

2023-05-04 17:08 UTC, NahuelDev commented on src/sidebarLearn.json
Hola, mil disculpas! Ahi lo revertí

2023-05-06 19:27 UTC, carburo requested changes
¡Hola, @NahuelDev! Gracias por contribuir a la traducción de esta página particularmente extensa. Te he dejado algunas sugerencias que puedes aplicar directamente desde la interfaz de GitHub si estás de acuerdo con ellas. También puedes dejar comentarios cuando tengas dudas o no estés de acuerdo con alguna de ellas.

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Ahora edita el campo de texto para que diga `abc`. Si lo hace lo suficientemente rápido, verá `Programar mensaje "ab"` seguido inmediatamente de `Cancelar mensaje "ab"` y `Programar mensaje "abc"`. *
```suggestion
Ahora edita el campo de texto para que diga `abc`. Si lo haces lo suficientemente rápido, verás `Programar mensaje "ab"` seguido inmediatamente de `Cancelar mensaje "ab"` y `Programar mensaje "abc"`. **React siempre limpia el Efecto del renderizado anterior antes de ejecutar el Efecto del siguiente renderizdo.** Es por eso que incluso si escribes rápidamente en el campo de texto, hay como máximo un temporizador programado a la vez. Edita el campo varias veces y observa la consola para tener una idea de cómo se limpian los Efectos.
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Tres segundos después, deberías ver una secuencia de mensajes (`a`, `ab`, `abc`, `abcd`, and `abcde`) en vez de cinco mensajes `abcde`. **Cada Efecto "captura" el valor de `text` desde su correspondi
```suggestion
Tres segundos después, deberías ver una secuencia de mensajes (`a`, `ab`, `abc`, `abcd`, and `abcde`) en vez de cinco mensajes `abcde`. **Cada Efecto "captura" el valor de `text` desde su correspondiente renderizado.**  No importa que el estado `text` haya cambiado: un Efecto del renderizado hecho con `text = 'ab'` siempre verá `'ab'`. En otras palabras, los Efectos de cada renderizado están aislados entre sí. Si tienes curiosidad acerca de cómo funciona esto puedes leer acerca de [clausuras](https://developer.mozilla.org/es/docs/Web/JavaScript/Closures).
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Veamos que es lo que sucede exactamente a medida que el usuario navega por la aplicación.
```suggestion
Veamos qué es lo que sucede exactamente a medida que el usuario navega por la aplicación.
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +**El Efecto *también* es una parte de la salida del renderizado.** El efecto del primer renderizado se convierte en:
```suggestion
**El Efecto *también* es una parte de la salida del renderizado.** El Efecto del primer renderizado se convierte en:
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +React actualiza el DOM para cambiar `"Bienvenido a general"` into `"Bienvenido a  travel"`.
```suggestion
React actualiza el DOM para cambiar `"Bienvenido a general"` a `"Bienvenido a travel"`.
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +**Antes de que React pueda aplicar el Efecto de la tercera renderización, necesita limpiar el último efecto que se _ejecutó_.** El Efecto de la segunda renderización fue omitido, por lo que React nec
Creo que así se transmite mejor el énfasis que se intenta poner en el original.
```suggestion
**Antes de que React pueda aplicar el Efecto de la tercera renderización, necesita limpiar el último Efecto que _sí_ se ejecutó.** El Efecto de la segunda renderización fue omitido, por lo que React necesita limpiar el Efecto de la primer renderización. Si te desplazas hacia arriba hasta la primera renderización, verás que su limpieza llama a `disconnect()` en la conexión que se creó con `createConnection('general')`. Esto desconecta la aplicación de la sala de chat `'general'`.
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Después de eso, React ejecuta el Efecto del tercer renderizado. Que conecta a la sala de chat `'travel'`.
```suggestion
Después de eso, React ejecuta el Efecto del tercer renderizado que conecta a la sala de chat `'travel'`.
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Cuando el [Modo Estricto](/reference/react/StrictMode) esta activado, React vuelve a montar cada componente después de montarlo por primera vez (el estado y DOM se conservan). Esto [te ayuda a encont
```suggestion
Cuando el [Modo Estricto](/reference/react/StrictMode) está activado, React vuelve a montar cada componente después de montarlo por primera vez (el estado y DOM se conservan). Esto [te ayuda a encontrar Efectos que necesitan limpieza](#step-3-add-cleanup-if-needed) y expone tempranamente errores como las condiciones de carrera. Adicionalmente, React vuelve a montar los Efectos cada vez que guardas el archivo en desarrollo. Ambos comportamientos solo suceden en modo de desarrollo.
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Usa el método [`focus()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) del input para hacer que `MyInput` se enfoque automáticamente cuando aparece en pantalla. Ya hay una impl
```suggestion
Usa el método [`focus()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) del input para hacer que `MyInput` se enfoque automáticamente cuando aparece en pantalla. Ya hay una implementación comentada, pero no funciona correctamente. Descubre por qué no funciona y corrígelo. (Si estás familiarizado con el atributo `autoFocus`, pretende que no existe: estamos reimplementando la misma funcionalidad desde cero.)
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Este componente muestra la biografía de la persona seleccionada. Carga la biografíá llamando a una función asíncrona `fetchBio(person)` al montar y cuando `person` cambia. Esa función asíncrona devue
```suggestion
Este componente muestra la biografía de la persona seleccionada. Carga la biografía llamando a una función asíncrona `fetchBio(person)` al montar y cuando `person` cambia. Esa función asíncrona devuelve una [promesa](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Promise) que eventualmente se resuelve a un string. Cuando la solicitud está hecha, se llama a `setBio` para mostrar el string debajo del elemento select.
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Cada Efecto de renderización tiene su propia variable `ignore`. Inicialmente, la variable `ignore` es `false`. Sin embargo, si un Efecto hace una limpieza (como cuando seleccionas una persona diferen
```suggestion
El Efecto de cada uno de los renderizados tiene su propia variable `ignore`. Inicialmente, la variable `ignore` es `false`. Sin embargo, si un Efecto hace una limpieza (como cuando seleccionas una persona diferente), su variable `ignore` pasa a ser `true`. Entonces, ahora no importa en qué orden se completen las solicitudes. Solo el Efecto de la última persona tendrá `ignore` configurado como `false`, por lo que llamará a `setBio(result)`. Los Efectos anteriores han sido limpiados, por lo que la comprobación `if (!ignore)` evitará que llamen a `setBio`:
```

2023-05-06 19:27 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +- Seleccionar a `'Taylor'` desencadena `fetchBio('Taylor')` **y limpia el anterior (Bob's) Efecto**
```suggestion
- Seleccionar a `'Taylor'` desencadena `fetchBio('Taylor')` **y limpia el anterior Efecto (de Bob)**
```

2023-05-06 19:28 UTC, carburo requested changes
¡Hola, @NahuelDev! Gracias por contribuir a la traducción de esta página particularmente extensa. Te he dejado algunas sugerencias que puedes aplicar directamente desde la interfaz de GitHub si estás de acuerdo con ellas. También puedes dejar comentarios cuando tengas dudas o no estés de acuerdo con alguna de ellas.

2023-05-06 22:06 UTC, NahuelDev commented on src/content/learn/synchronizing-with-effects.md
> +Ahora edita el campo de texto para que diga `abc`. Si lo hace lo suficientemente rápido, verá `Programar mensaje "ab"` seguido inmediatamente de `Cancelar mensaje "ab"` y `Programar mensaje "abc"`. *
Hola @carburo! Gracias por las sugerencias (algunas hasta me dan verguenza haberlas cometido, tuve que haber revisado mejor) acepté todas menos esta que escribiste renderizdo

2023-05-06 22:17 UTC, carburo commented on src/content/learn/synchronizing-with-effects.md
> +Ahora edita el campo de texto para que diga `abc`. Si lo hace lo suficientemente rápido, verá `Programar mensaje "ab"` seguido inmediatamente de `Cancelar mensaje "ab"` y `Programar mensaje "abc"`. *
Corregido, ¡gracias! :sweat_smile:

2023-05-06 22:18 UTC, carburo approved these changes
Listo ¡Muchas gracias! 🚀

2023-05-06 22:18 UTC, merged