added meetups translations
reactjs/es.react.dev pull request #691
Opened 2023-05-09 21:33 UTC by ilichpadilla

Hola @carburo,
Este es el PR de **Community Meetups** traducido al español. 
Me dejas saber si necesita algún cambio adicional.

2023-05-10 05:11 UTC, mateoguzmana requested changes
¡Hola, @ilichpadilla!

Gracias por la contribución. Te dejé un par de comentarios para que analices. Siéntete libre de decir si no estás de acuerdo con alguno.

Podrías también darle una segunda revisión? Noté que hay una mezcla grande entre los nombres de las ciudades en Español e Inglés. Para mantener consistencia, deberíamos traducir los nombres que tengan traducción al Español.

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +## Dinamarka {/*denmark*/}
```suggestion
## Dinamarca {/*denmark*/}
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [Sao Paulo](https://www.meetup.com/pt-BR/ReactJS-SP/)
```suggestion
* [São Paulo](https://www.meetup.com/pt-BR/ReactJS-SP/)
```

La podrías dejar con el nombre en Portugués, o hacerla ponerla completamente en castellano. Te dejo esta referencia
https://es.wikipedia.org/wiki/S%C3%A3o_Paulo

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [React.JS Chicas Londres](https://www.meetup.com/ReactJS-Girls-London/)
```suggestion
* [React.JS Girls London](https://www.meetup.com/ReactJS-Girls-London/)
```

Es un nombre propio, lo dejaría como es originalmente

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [React Londres : Trae tu Propio Proyecto](https://www.meetup.com/React-London-Bring-Your-Own-Project/)
```suggestion
* [React Londres: Trae tu propio proyecto](https://www.meetup.com/React-London-Bring-Your-Own-Project/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [Charlotte, NC - React Nativo](https://www.meetup.com/cltreactnative/)
```suggestion
* [Charlotte, NC - React Native](https://www.meetup.com/cltreactnative/)
```

_React Native_ no debe ser traducido ya que es un nombre propio

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [Detroit, MI - Detroit React Grupo de Usuario](https://www.meetup.com/Detroit-React-User-Group/)
```suggestion
* [Detroit, MI - Grupo de Usuarios de React en Detroit](https://www.meetup.com/Detroit-React-User-Group/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [Los Angeles, CA - React Nativo](https://www.meetup.com/React-Native-Los-Angeles/)
```suggestion
* [Los Angeles, CA - React Native](https://www.meetup.com/React-Native-Los-Angeles/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [New York, NY - React Nativo](https://www.meetup.com/React-Native-NYC/)
```suggestion
* [New York, NY - React Native](https://www.meetup.com/React-Native-NYC/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [New York, NY - Damas React](https://www.meetup.com/React-Ladies/)
```suggestion
* [New York, NY - React Ladies](https://www.meetup.com/React-Ladies/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [New York, NY - React Nativo](https://www.meetup.com/React-Native-NYC/)
```suggestion
* [New York, NY - React Native](https://www.meetup.com/React-Native-NYC/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [Omaha, NE - ReactJS/React Nativo](https://www.meetup.com/omaha-react-meetup-group/)
```suggestion
* [Omaha, NE - ReactJS/React Native](https://www.meetup.com/omaha-react-meetup-group/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [Palo Alto, CA - React Nativo](https://www.meetup.com/React-Native-Silicon-Valley/)
```suggestion
* [Palo Alto, CA - React Native](https://www.meetup.com/React-Native-Silicon-Valley/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [Pittsburgh, PA - ReactJS/React Nativo](https://www.meetup.com/ReactPgh/)
```suggestion
* [Pittsburgh, PA - ReactJS/React Native](https://www.meetup.com/ReactPgh/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [San Francisco - React Mundo Real](https://www.meetup.com/Real-World-React)
```suggestion
* [San Francisco - Real World React](https://www.meetup.com/Real-World-React)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [San Francisco, CA - React Nativo](https://www.meetup.com/React-Native-San-Francisco/)
```suggestion
* [San Francisco, CA - React Native](https://www.meetup.com/React-Native-San-Francisco/)
```

2023-05-10 05:11 UTC, mateoguzmana commented on src/content/community/meetups.md
> +* [Seattle, WA - React Nativo](https://www.meetup.com/Seattle-React-Native-Meetup/)
```suggestion
* [Seattle, WA - React Native](https://www.meetup.com/Seattle-React-Native-Meetup/)
```

2023-05-10 21:27 UTC, ilichpadilla commented
Gracias @mateoguzmana 
Le estaré realizando las sugerencias y revisando los nombres.

2023-05-11 04:27 UTC, ilichpadilla commented
Hola @mateoguzmana 

Realicé varios cambios, favor revisar.

2023-05-11 06:19 UTC, mateoguzmana approved these changes
Se ve genial, ¡gracias! @ilichpadilla

2023-05-11 06:19 UTC, merged