Translate `/community/videos` page
reactjs/es.react.dev pull request #697
Opened 2023-05-15 14:13 UTC by AFBGDeveloper

Traducción de la página `/community/videos` completada. [New Translation Progress Checklist (comment)](https://github.com/reactjs/es.react.dev/issues/500#issuecomment-1545003540)

Quedo atento a cualquier corrección.

2023-05-17 19:55 UTC, mateoguzmana requested changes
¡Gracias por contribuir @AFBGdev! 

Te dejé unos comentarios pequeños. También noté que `inglés` lo escribiste sin tilde en varias ocasiones. Te dejé una corrección de eso en unas lineas pero por favor dale una segunda revisada porque vi más.

2023-05-17 19:55 UTC, mateoguzmana commented on src/content/community/videos.md
> +Para un demo de actualizar a React 18, mira la charla de [Shruti Kapoor](https://twitter.com/shrutikapoor08) aquí:
```suggestion
Para ver un demo de cómo actualizar a React 18, mira la charla de [Shruti Kapoor](https://twitter.com/shrutikapoor08) aquí:
```

2023-05-17 19:55 UTC, mateoguzmana commented on src/content/community/videos.md
> +Para React 18, hemos creado nuestro primer Grupo de Trabajo para colaborar con un comité de expertos, desarrolladores, mantenedores de biblioteca, y educadores. Juntos hemos trabajado para crear nues
```suggestion
Para React 18, hemos creado nuestro primer grupo de trabajo para colaborar con un comité de expertos, desarrolladores, mantenedores de biblioteca, y educadores. Juntos hemos trabajado para crear nuestra estrategia de adopción gradual y para refinar nuestras APIs como `useId`, `useSyncExternalStore`, y `useInsertionEffect`.
```

2023-05-17 19:55 UTC, mateoguzmana commented on src/content/community/videos.md
> +Para una descripción general sobre este trabajo, mira la charla de [Aakansha' Doshi](https://twitter.com/aakansha1216):
```suggestion
Para ver una descripción general sobre este trabajo, mira la charla de [Aakansha' Doshi](https://twitter.com/aakansha1216):
```

2023-05-17 19:55 UTC, mateoguzmana commented on src/content/community/videos.md
> +### Herramientas de Desarrollo de React {/*react-developer-tooling*/}
```suggestion
### Herramientas de desarrollo de React {/*react-developer-tooling*/}
```

2023-05-17 19:55 UTC, mateoguzmana commented on src/content/community/videos.md
> +* Debbie O'Brien: [Cosas que aprender desde la nueva documentación de React (en ingles, subtítulos en español)](https://youtu.be/-7odLW_hG7s).
```suggestion
* Debbie O'Brien: [Cosas que aprender desde la nueva documentación de React (en inglés, subtítulos en español)](https://youtu.be/-7odLW_hG7s).
```

2023-05-17 19:55 UTC, mateoguzmana commented on src/content/community/videos.md
> +* Sarah Rainsberger: [Aprendiendo en el navegador (en ingles, subtítulos en español)](https://youtu.be/5X-WEQflCL0).
```suggestion
* Sarah Rainsberger: [Aprendiendo en el navegador (en inglés, subtítulos en español)](https://youtu.be/5X-WEQflCL0).
```

2023-05-17 19:55 UTC, mateoguzmana commented on src/content/community/videos.md
> +* Linton Ye: [El Retorno de Inversión de diseñar con React (en ingles, subtítulos en español)](https://youtu.be/7cPWmID5XAk).
```suggestion
* Linton Ye: [El Retorno de inversión de diseñar con React (en inglés, subtítulos en español)](https://youtu.be/7cPWmID5XAk).
```

2023-05-17 22:28 UTC, AFBGdev commented
Mucha gracias por tu revisión y sugerencias. Ahora empiezo con los cambios. ☺️

2023-05-18 07:03 UTC, AFBGdev commented
Buen día @mateoguzmana. He realizado los cambios solicitados.

Quedo atento a cualquier corrección.

2023-05-18 07:03 UTC, mateoguzmana approved these changes

2023-05-18 07:04 UTC, merged