translate: adding interactivity to spanish
reactjs/es.react.dev pull request #698
Opened 2023-05-17 02:17 UTC by joelnbl

* Adding translation to interactivity to Spanish

* Updating translation to in sidebar of interactivity to Spanish text to Spanish

2023-05-17 19:11 UTC, joelnbl commented
Sigue todos los estándares

2023-05-19 20:30 UTC, joelnbl commented
@carburo what's the status?

2023-05-23 02:44 UTC, carburo commented
Hi! A review from one of the maintainers is still pending before we can merge it. I, personally, haven't had the time to take a look at it yet. Sorry for the inconvenience.

2023-05-24 14:40 UTC, joelnbl commented
@carburo there is an error with the site lint

2023-05-24 17:05 UTC, carburo requested changes
¡Hola! ¡Gracias por tu contribución! Además de las sugerencias de código hay algunos elementos que deberías revisar antes de que podamos mezclar este PR.

* El uso de «usted» para la segunda persona del singular. Para mantener la consistencia en la documentación y porque es menos propenso a ambigüedades hemos optado por usar siempre «tú» (Puedes consultar nuestra [guía de traducción](https://github.com/reactjs/es.reactjs.org/blob/master/TRANSLATION.md#style-guide) para otros aspectos como este).
* Los títulos de las secciones deben coincidir con el de la página a la que referencian. Por ejemplo: la sección se titula «Respondiendo a eventos» mientras el título de la página es «Responder a eventos».
* *Array* no se traduce (ver https://github.com/reactjs/es.react.dev/wiki/Glosario)

2023-05-24 17:05 UTC, carburo commented on src/content/learn/adding-interactivity.md
> +Por lo general, usará la sintaxis de extensión `...` para copiar objetos y matrices que desea cambiar. Por ejemplo, actualizar un objeto anidado podría verse así:
https://github.com/reactjs/es.react.dev/wiki/Glosario
```suggestion
Por lo general, usará la sintaxis de propagación `...` para copiar objetos y matrices que desea cambiar. Por ejemplo, actualizar un objeto anidado podría verse así:
```

2023-05-24 17:05 UTC, carburo commented on src/content/learn/adding-interactivity.md
> +## ¿Que sigue? {/*whats-next*/}
```suggestion
## ¿Qué sigue? {/*whats-next*/}
```

2023-05-24 17:18 UTC, joelnbl commented
@carburo fixed!

2023-05-24 17:23 UTC, carburo commented
@joelnbl Por favor, haz una revisión completa del documento. Aún quedan conjugaciones con la forma de «usted». También haz la revisión de todas las secciones. Sin hacer una revisión exhaustiva puedo ver que hay una sección que se llama «Renderizar y confirmar» y la página  «Renderizado y confirmación»

2023-05-24 18:17 UTC, joelnbl commented
@carburo ready for review

2023-05-24 23:46 UTC, carburo approved these changes

2023-05-24 23:55 UTC, merged