Translate "Separating events from effects"
reactjs/es.react.dev pull request #711
Opened 2023-06-06 00:32 UTC by danmondra

2023-06-14 20:03 UTC, mateoguzmana requested changes
¡Gracias por la contribución @danmondra!

Veo que el build falla, podrías confirmar que todo está bien corriendo el proyecto localmente? 

Te dejo también unos comentarios pequeños. Te hago una segunda revisión apenas esta parte esté bien.

Si necesitas alguna ayuda, me avisas.

2023-06-14 20:03 UTC, mateoguzmana commented on src/content/learn/separating-events-from-effects.md
> +
```suggestion

```

2023-06-14 20:03 UTC, mateoguzmana commented on src/content/learn/separating-events-from-effects.md
> +
```suggestion

```

2023-06-14 20:03 UTC, mateoguzmana commented on src/content/learn/separating-events-from-effects.md
> +
```suggestion

```

2023-06-14 20:03 UTC, mateoguzmana commented on src/content/learn/separating-events-from-effects.md
> +
```suggestion

```

2023-06-14 20:03 UTC, mateoguzmana commented on src/content/learn/separating-events-from-effects.md
> +
```suggestion

```

2023-06-14 20:03 UTC, mateoguzmana commented on src/content/learn/separating-events-from-effects.md
> +
```suggestion

```

2023-06-14 20:03 UTC, mateoguzmana commented on src/content/learn/separating-events-from-effects.md
> +
```suggestion

```

2023-06-16 13:20 UTC, nghsoftware commented
Según la Guía de estilo https://github.com/reactjs/es.react.dev/wiki/Gu%C3%ADa-de-estilo#el-gerundio, deberías evitar el gerundio (verbos terminados en -ndo, según la RAE: https://dle.rae.es/gerundio) en los títulos (y por continuidad de criterio en los subtítulos), por ello recomiendo algunos cambios.

2023-06-16 13:44 UTC, nghsoftware reviewed
Esto es lo que encontré según el criterio del uso de gerundios https://github.com/reactjs/es.react.dev/wiki/Gu%C3%ADa-de-estilo#el-gerundio

2023-06-16 13:44 UTC, nghsoftware commented on src/content/learn/separating-events-from-effects.md
> +title: 'Separando Eventos de los Efectos'
title: 'Separar Eventos de los Efectos'

2023-06-16 13:44 UTC, nghsoftware commented on src/content/learn/separating-events-from-effects.md
> +## Eligiendo entre controladores de eventos y Efectos {/*choosing-between-event-handlers-and-effects*/}
## Eligir entre controladores de eventos y Efectos

2023-06-16 13:44 UTC, nghsoftware commented on src/content/learn/separating-events-from-effects.md
> +## Extrayendo lógica no reactiva fuera de los Efectos {/*extracting-non-reactive-logic-out-of-effects*/}
## Extraer lógica no reactiva fuera de los Efectos

2023-06-16 13:44 UTC, nghsoftware commented on src/content/learn/separating-events-from-effects.md
> +### Leyendo las últimas propiedades y el estado con los Eventos de Efecto {/*reading-latest-props-and-state-with-effect-events*/}
### Leer las últimas propiedades y el estado con los Eventos de Efecto

2023-06-16 14:02 UTC, nghsoftware commented on src/content/learn/separating-events-from-effects.md
> +### Leyendo las últimas propiedades y el estado con los Eventos de Efecto {/*reading-latest-props-and-state-with-effect-events*/}
```suggestion
### Leer las últimas propiedades y el estado con los Eventos de Efecto {/*reading-latest-props-and-state-with-effect-events*/}
```

2023-06-16 19:33 UTC, danmondra commented on src/content/learn/separating-events-from-effects.md
> +### Leyendo las últimas propiedades y el estado con los Eventos de Efecto {/*reading-latest-props-and-state-with-effect-events*/}
Gracias por la corrección, en un momento lo cambio.

2023-06-20 05:04 UTC, danmondra commented
> ¡Gracias por la contribución @danmondra!
> 
> Veo que el build falla, podrías confirmar que todo está bien corriendo el proyecto localmente?
> 
> Te dejo también unos comentarios pequeños. Te hago una segunda revisión apenas esta parte esté bien.
> 
> Si necesitas alguna ayuda, me avisas.

2023-06-20 05:04 UTC, closed without merging

2023-06-20 05:04 UTC, danmondra commented
Ya corregí los errores mencionados y otros encontrados. Revisé el build y si compila localmente sin problemas.