Update you-might-not-need-an-effect.md
reactjs/es.react.dev pull request #841
Opened 2023-07-18 08:49 UTC by Vicenciomf1

¡Hola! Hice la traducción de la parte de contenido de "you might not need an effect", no obstante, aún no está terminada la parte de desafíos, si nadie más de la comunidad se ofrece a traducirlo de aquí al jueves, puedo terminarla para entregar tal parte en forma.
Espero tengan una buena semana, ¡saludos!

2023-07-19 01:17 UTC, NGHdeveloper approved these changes
En progreso aún sin finalizar

2023-07-19 01:17 UTC, NGHdeveloper commented on src/content/learn/you-might-not-need-an-effect.md
> +Puedes almacenar en caché (o ["memoizar"](https://es.wikipedia.org/wiki/Memoización)) un cálculo costoso envolviéndolo en un Hook de React [`useMemo`](/reference/react/useMemo):
```suggestion
Tú puedes almacenar en caché (o ["memoizar"](https://es.wikipedia.org/wiki/Memoización)) un cálculo costoso envolviéndolo en un Hook de React [`useMemo`](/reference/react/useMemo):
```

2023-07-19 01:17 UTC, NGHdeveloper commented on src/content/learn/you-might-not-need-an-effect.md
> +O, escrito en una sola línea:
```suggestion
O, escrito como una línea simple:
```

2023-07-19 01:17 UTC, NGHdeveloper reviewed
En progreso aún sin finalizar, mañana continuo.

2023-07-19 01:26 UTC, NGHdeveloper requested changes
En progreso aún sin finalizar, mañana continúo.

2023-07-20 00:02 UTC, NGHdeveloper requested changes
Corrección parcial, mañana continúo.

2023-07-20 00:02 UTC, NGHdeveloper requested changes
Corrección parcial, mañana continúo.

2023-07-20 02:58 UTC, carburo commented on src/content/learn/you-might-not-need-an-effect.md
> +title: 'Quizá no necesites un Efecto'
En el glosario se especifica que _Effect_ se traducirá como Efecto. Si deseas cambiarlo, por favor, abre un hilo de debate primero.

2023-07-21 03:10 UTC, NGHdeveloper reviewed
Hasta la línea 459, corregido con la ayuda de la IA, realmente es muy buena y precisa tanto en la traducción como en la adecuación para mejor comprensión, mañana continúo.

2023-07-21 03:10 UTC, NGHdeveloper commented on src/content/learn/you-might-not-need-an-effect.md
> +Recuerda que dentro de los manejadores de eventos, [el estado se comporta como una instantánea.](/learn/state-as-a-snapshot) Por ejemplo, incluso después de llamar a `setRound(round + 1)`, la variabl
```suggestion
Recuerda que dentro de los controladores de eventos, [el estado se comporta como una instantánea.](/learn/state-as-a-snapshot) Por ejemplo, incluso después de llamar a `setRound(round + 1)`, la variable `round` reflejará el valor en el momento en que el usuario hizo clic en el botón. Si necesitas usar el siguiente valor para cálculos, defínelo manualmente como `const nextRound = round + 1`.
```

2023-07-21 03:10 UTC, NGHdeveloper commented on src/content/learn/you-might-not-need-an-effect.md
> +En algunos casos, *no puedes* calcular el siguiente estado directamente en el manejador de eventos. Por ejemplo, imagina un formulario con múltiples desplegables donde las opciones del siguiente desp
```suggestion
En algunos casos, *no puedes* calcular el siguiente estado directamente en el controlador de eventos. Por ejemplo, imagina un formulario con múltiples menús desplegables donde las opciones del siguiente menú desplegable dependen del valor seleccionado en el menú desplegable anterior. En este caso, una cadena de Efectos es apropiada porque estás sincronizando con la red.
```

2023-07-21 03:10 UTC, NGHdeveloper commented on src/content/learn/you-might-not-need-an-effect.md
> +Algunas lógicas sólo deben ejecutarse una vez cuando se carga la aplicación.
```suggestion
Alguna lógica solo debería ejecutarse una vez cuando se carga la aplicación.
```

2023-07-21 03:10 UTC, NGHdeveloper commented on src/content/learn/you-might-not-need-an-effect.md
> +Podrías estar tentado a colocarla en un Efecto en el componente de nivel superior:
```suggestion
Podrías sentirte tentado a colocarla en un Efecto en el componente de nivel superior:
```

2023-07-21 03:11 UTC, NGHdeveloper reviewed
Hasta la línea 459, corregido con la ayuda de la IA, realmente es muy buena y precisa tanto en la traducción como en la adecuación para mejor comprensión, mañana continúo.

2023-07-21 03:14 UTC, NGHdeveloper reviewed
.

2023-07-21 20:03 UTC, NGHdeveloper requested changes
Pido disculpas por la demora en la revisión, pero realmente fue extensa y exhaustiva, observe traducciones erróneas en conceptos como "carga de datos" en lugar de obtención de datos, "fuente de datos externa" en lugar de "almacén de datos externos", además de algunas inconsistencias en "levantar el estado", anglicismos, etc., muchas de las correcciones son simples cambios en los tiempos verbales, la aplicación de signos de puntuación, uso de sinónimos, etc., esto es porque trabaje con IA y le indique que la traducción fuera en un contexto de programación, académico, comprensivo, textual y consistente en React.
Si es demasiado extenso para hacer los _commits_ correspondientes en cada corrección, no tengo ningún problema en hacerlo yo mismo, pero me gustaría tener su opinión general si el criterio fue el correcto.

2023-07-21 20:03 UTC, NGHdeveloper requested changes
Pido disculpas por la demora en la revisión, pero realmente fue extensa y exhaustiva, observe traducciones erróneas en conceptos como "carga de datos" en lugar de obtención de datos, "fuente de datos externa" en lugar de "almacén de datos externos", además de algunas inconsistencias en "levantar el estado", anglicismos, etc., muchas de las correcciones son simples cambios en los tiempos verbales, la aplicación de signos de puntuación, uso de sinónimos, etc., esto es porque trabaje con IA y le indique que la traducción fuera en un contexto de programación, académico, comprensivo, textual y consistente en React.
Si es demasiado extenso para hacer los _commits_ correspondientes en cada corrección, no tengo ningún problema en hacerlo yo mismo, pero me gustaría tener su opinión general si el criterio fue el correcto.

2023-07-22 18:55 UTC, NGHdeveloper requested changes

2023-07-22 18:55 UTC, NGHdeveloper commented on src/content/learn/you-might-not-need-an-effect.md
> +  // 🔴 Evitar: Pasar datos de hijo a padre en un Efecto
```suggestion
  // 🔴 Evitar: Pasar datos al padre en un Efecto
```

2023-07-23 03:26 UTC, Vicenciomf1 commented
Hola! También consulté en lo que tenía dudas de anglicismo, y la IA o deepL me decían que usará obtención de datos, no obstante, en contextos laborales y en la comunidad en español en general se usa el anglicismo fetch, pero en traducciones en escape hatches se encuentra tanto el uso del verbo "fetch" como de "obtener", hay un capítulo que tradujo carburo en donde se usa "obtener datos", creo entonces que podría ser importante agregarlo en el glosario, además de otros verbos que aparecen acá como network o build. ¡Saludos!

2023-07-23 17:53 UTC, NGHdeveloper approved these changes
Revisión finalizada, procedo al mezclado.

2023-07-23 17:59 UTC, merged