Update experimental_taintUniqueValue.md
reactjs/es.react.dev pull request #889
Opened 2023-10-27 10:37 UTC by 05hiteshbansal

translated in spanish from english

2023-10-27 10:38 UTC, 05hiteshbansal commented
@henrik  please review my PR and merge it

2023-10-27 12:09 UTC, 05hiteshbansal commented
@sunny  @benschwarz  please review and merge my PR

2023-10-27 14:30 UTC, 05hiteshbansal commented
@NGHdeveloper please review and merge my PR

2023-10-27 16:15 UTC, sunny commented
Hi @05hiteshbansal, please do not spam accounts asking for merges, it’s not very good etiquette 🙏🏻

Asking one person at a time and waiting for a few days before asking someone else would be preferable.

2023-10-27 16:24 UTC, 05hiteshbansal commented
sorry . I didn't mean to do that @sunny

2023-10-28 16:31 UTC, 05hiteshbansal commented
@NGHdeveloper please review my PR

2023-10-29 15:14 UTC, carburo commented
¡Hola, @05hiteshbansal! Muchas gracias por tu contribución. Como ya dijo sunny en el comentario anterior no hay necesidad de hacer ping constantemente para la revisión. Este es un proyecto totalmente conducido por contribuidores voluntarios durante nuestro tiempo libre y por tanto no podemos atender las revisiones inmediatamente. El PR aún no está listo para mezclarse, porque existen algunos detalles que necesitas revisar:

- Hay secciones como «Parameters», «Returns» y «Caveats» sin traducir (Revisa primero el [glosario](https://github.com/reactjs/es.react.dev/wiki/Glosario#secciones-comunes) para utilizar el término estandarizado en esta traducción).
- Hay partes del contenido del texto sin traducir. Por ejemplo: «**Do not rely solely on tainting for security.**»
- El uso de «usted» para la segunda persona del singular. Para mantener la consistencia en la documentación y porque es menos propenso a ambigüedades hemos optado por usar siempre «tú» (Puedes consultar nuestra [guía de estilo](https://github.com/reactjs/es.react.dev/wiki/Guía-de-estilo]) para otros aspectos como este).
- Deben mantenerse los mismos números de líneas entre la traducción y el original para evitar conflictos en Git en futuras actualizaciones del texto original. (Por ejemplo el texto de la línea 134 debió estar en la línea 133).

2023-10-29 15:31 UTC, carburo requested changes
¡Hola, @05hiteshbansal! Muchas gracias por tu contribución. Como ya dijo sunny en el comentario anterior no hay necesidad de hacer ping constantemente para la revisión. Este es un proyecto totalmente conducido por contribuidores voluntarios durante nuestro tiempo libre y por tanto no podemos atender las revisiones inmediatamente. El PR aún no está listo para mezclarse, porque existen algunos detalles que necesitas revisar:

Hay secciones como «Parameters», «Returns» y «Caveats» sin traducir (Revisa primero el [glosario](https://github.com/reactjs/es.react.dev/wiki/Glosario#secciones-comunes) para utilizar el término estandarizado en esta traducción).
Hay partes del contenido del texto sin traducir. Por ejemplo: «Do not rely solely on tainting for security.»
El uso de «usted» para la segunda persona del singular. Para mantener la consistencia en la documentación y porque es menos propenso a ambigüedades hemos optado por usar siempre «tú» (Puedes consultar nuestra [guía de estilo](https://github.com/reactjs/es.react.dev/wiki/Gu%C3%ADa-de-estilo%5D) para otros aspectos como este).
Deben mantenerse los mismos números de líneas entre la traducción y el original para evitar conflictos en Git en futuras actualizaciones del texto original. (Por ejemplo el texto de la línea 134 debió estar en la línea 133).

2023-10-29 15:35 UTC, 05hiteshbansal commented
can you please elaborate more on where should I have to use "you" @carburo

2023-10-29 15:58 UTC, carburo commented
@05hiteshbansal las razones están explicadas en el glosario. Ten en cuenta que está permitido utilizar una herramienta de traducción automática siempre y cuando se utilice como base y no como resultado final. El texto siempre debe ser revisado por una persona antes de enviarse. Si no cuentas con el dominio de la lengua, entonces este último paso no será posible.

2023-10-29 16:01 UTC, carburo commented
Aquí está el enlace a la sección sobre el uso de la segunda persona del singular: https://github.com/reactjs/es.react.dev/wiki/Guía-de-estilo#usted-tú-y-vos

2023-11-14 04:26 UTC, closed without merging